services:

  pdfdb:
    image: postgres:14
    container_name: pdf-postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: .
    container_name: pdf-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - pdfdb

volumes:
  pgdata:
