services:
  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: pdfdb
      POSTGRES_USER: pdfuser
      POSTGRES_PASSWORD: pdfpass
    ports:
      - "5432:5432"

  backend:
    build: .
    container_name: django
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres