# Generated by Django 3.1.12 on 2025-06-28 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfhandler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationhistory',
            name='operation_type',
            field=models.CharField(choices=[('merge', 'Merge'), ('split', 'Split'), ('extract', 'Extract'), ('remove_pages', 'Remove Pages'), ('remove_password', 'Remove Password'), ('compress_and_zip', 'Compress to ZIP')], max_length=50),
        ),
    ]
