# Generated by Django 4.2.7 on 2025-06-05 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfhandler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mergehistory',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
