# Generated by Django 4.2.7 on 2025-05-06 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfhandler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
