# Generated by Django 5.2.3 on 2025-06-30 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfhandler', '0004_alter_operationhistory_result_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationhistory',
            name='operation_type',
            field=models.CharField(choices=[('merge', 'Merge'), ('split', 'Split'), ('extract', 'Extract'), ('remove_pages', 'Remove Pages'), ('remove_password', 'Remove Password'), ('compress', 'Compress to ZIP')], max_length=50),
        ),
    ]
