name: CI/CD for PdfApp

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  lint-and-test:
    name: Lint & Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_DB: pdfdb
          POSTGRES_USER: pdfuser
          POSTGRES_PASSWORD: pdfpass
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      POSTGRES_DB: pdfdb
      POSTGRES_USER: pdfuser
      POSTGRES_PASSWORD: pdfpass
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      TEST: true
      DJANGO_SETTINGS_MODULE: pdfapp.settings.dev

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Write SECRET_KEY to .env
      run: echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" > .env

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8 pytest pytest-django python-dotenv

    - name: Run flake8 (lint)
      run: flake8 .

    - name: Apply migrations
      working-directory: ./pdfapp
      run: |
        export PYTHONPATH=$PYTHONPATH:$(pwd)
        python manage.py migrate

    - name: Run Django tests
      working-directory: ./pdfapp
      run: |
        export PYTHONPATH=$PYTHONPATH:$(pwd)
        pytest

  deploy:
    name: Deploy to AWS (test)
    needs: lint-and-test
    runs-on: ubuntu-latest
#    if: github.ref == 'refs/heads/main' #test

    env:
      AWS_ACCOUNT_ID: 384782264249
      AWS_REGION:    eu-north-1
      ECR_REPOSITORY:    pdfapp
      ECS_CLUSTER:       ${{ secrets.ECS_CLUSTER }}
      ECS_SERVICE_NAME:  ${{ secrets.ECS_SERVICE_NAME }}
      ECS_TASK_FAMILY:   ${{ secrets.ECS_TASK_FAMILY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ${{ env.AWS_REGION }}

      - name: Ensure ECR repo exists
        run: |
          set -e
          REGION=${AWS_REGION}
          REPO_NAME=${ECR_REPOSITORY}

          echo "Checking ECR repository: $REPO_NAME"
          if ! aws ecr describe-repositories --repository-names "$REPO_NAME" --region "$REGION" >/dev/null 2>&1; then
            echo "Repository $REPO_NAME does not exist. Creating..."
            aws ecr create-repository --repository-name "$REPO_NAME" --region "$REGION"
          else
            echo "Repository $REPO_NAME exists."
          fi

      - name: Set image tags
        id: set-tags
        run: |
          DJANGO_IMAGE_TAG="django-${GITHUB_SHA}"
          NGINX_IMAGE_TAG="nginx-${GITHUB_SHA}"

          DJANGO_IMAGE_URI="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPOSITORY}:${DJANGO_IMAGE_TAG}"
          NGINX_IMAGE_URI="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPOSITORY}:${NGINX_IMAGE_TAG}"

          echo "DJANGO_IMAGE_URI=$DJANGO_IMAGE_URI" >> $GITHUB_ENV
          echo "NGINX_IMAGE_URI=$NGINX_IMAGE_URI" >> $GITHUB_ENV

      - name: Debug image URIs from outputs
        run: |
          echo "DJANGO_IMAGE_URI=${{ steps.set-tags.outputs.django_image_uri }}"
          echo "NGINX_IMAGE_URI=${{ steps.set-tags.outputs.nginx_image_uri }}"

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password \
            --region ${AWS_REGION} \
          | docker login \
            --username AWS \
            --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com

      - name: Build & Push Django Docker image
        run: |
          docker build -t $DJANGO_IMAGE_URI -f Dockerfile .
          docker push $DJANGO_IMAGE_URI

      - name: Collect static files for nginx
        run: |
          export DJANGO_SETTINGS_MODULE=pdfapp.settings.prod
          pip install -r requirements.txt
          python pdfapp/manage.py collectstatic --noinput

      - name: Prepare static files for nginx build
        run: |
          rm -rf nginx/staticfiles
          mkdir -p nginx/staticfiles
          cp -r pdfapp/staticfiles/* nginx/staticfiles/

- name: Build & Push Nginx Docker image
  run: |
    docker build -t $NGINX_IMAGE_URI -f nginx/Dockerfile nginx/
    docker push $NGINX_IMAGE_URI

      - name: Render ECS task definition
        id: render-task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: django
          image: ${{ env.DJANGO_IMAGE_URI }}
          environment-variables: |
            DJANGO_SETTINGS_MODULE=pdfapp.settings.prod
            POSTGRES_DB=${{ secrets.POSTGRES_DB }}
            POSTGRES_USER=${{ secrets.POSTGRES_USER }}
            POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
            POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}
            POSTGRES_PORT=${{ secrets.POSTGRES_PORT }}
            EMAIL=${{ secrets.EMAIL }}
            EMAIL_PASS=${{ secrets.EMAIL_PASS }}
            SECRET_KEY=${{ secrets.SECRET_KEY }}

      - name: Render ECS task definition for Nginx
        id: render-task-def-nginx
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ${{ steps.render-task-def.outputs.task-definition }}
          container-name: nginx
          image: ${{ env.NGINX_IMAGE_URI }}

      - name: Deploy to ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          cluster: ${{ env.ECS_CLUSTER }}
          service: ${{ env.ECS_SERVICE_NAME }}
          task-definition: ${{ steps.render-task-def.outputs.task-definition }}

